name: Build and publish
on: push

jobs:

  docker:
    name: Docker Hub
    runs-on: ubuntu-latest

    steps:
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: coldfix
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          build-args: FROM=certbot/certbot:latest
          load: true
          tags: |
            coldfix/test-repo:amd64-latest
            coldfix/test-repo:amd64-${{ github.ref_name }}

      - uses: docker/build-push-action@v2
        with:
          platforms: linux/arm64
          build-args: FROM=certbot/certbot:arm64v8-latest
          load: true
          tags: |
            coldfix/test-repo:arm64-latest
            coldfix/test-repo:arm64-${{ github.ref_name }}

      # push multi-arch images:

      - run: docker push -a coldfix/test-repo

      - run: docker manifest create
                coldfix/test-repo:latest
                coldfix/test-repo:amd64-latest
                coldfix/test-repo:arm64-latest

      - run: docker manifest push coldfix/test-repo:latest

      - run: docker manifest create
                coldfix/test-repo:${{ github.ref_name }}
                coldfix/test-repo:amd64-${{ github.ref_name }}
                coldfix/test-repo:arm64-${{ github.ref_name }}

      - run: docker manifest push coldfix/test-repo:${{ github.ref_name }}
