name: Build and publish
on: push

jobs:
  deploy:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install setup dependencies
        run: pip install wheel twine flake8

      - run: flake8

      - name: Build package
        run: python setup.py sdist bdist_wheel

      - name: Check distribution
        run: twine check dist/*

      - name: Publish package to PyPI
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: coldfix-deploy
          password: ${{ secrets.pypi_password }}
