name: Build and publish
on: push

jobs:
  pypi:
    name: PyPI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install setup dependencies
        run: pip install wheel twine flake8

      - run: flake8

      - name: Build package
        run: python setup.py sdist bdist_wheel

      - name: Check distribution
        run: twine check dist/*

      - name: Publish package to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: coldfix-deploy
          password: ${{ secrets.pypi_password }}

  docker:
    name: Docker Hub
    runs-on: ubuntu-latest

    steps:
      - id: meta
        uses: docker/metadata-action@v3
        with:
          images: coldfix/certbot-dns-netcup
          tags: |
            type=semver,pattern={{version}}

      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: coldfix
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          push: ${{ startsWith(github.ref, 'refs/tags/v') }}
          tags: ${{ steps.meta.outputs.tags }}
